---
- name: Deploy Minio package and configure user, update /etc/hosts, copy minio.env file, start Minio service
  hosts: minio  # Assuming 'minio' is the group containing Minio servers
  become: true  # To execute tasks with sudo
  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Start Minio service
      systemd:
        name: minio.service
        state: started
        enabled: yes

    - name: Check Minio service status
      systemd:
        name: minio.service
        state: restarted

